const DOM = {
    gameArea: document.getElementById('game-area'),
    uiArea: document.getElementById('ui-area'),
    lanesContainer: document.getElementById('lanes-container'),
    scoreEl: document.getElementById('score'),
    comboEl: document.getElementById('combo'),
    judgementTextEl: document.getElementById('judgement-text'),
    comboTextEl: document.getElementById('combo-text'),
    musicPlayer: document.getElementById('music-player'),
    countdownTextEl: document.getElementById('countdown-text'),
    noteCountContainer: document.getElementById('note-count-container'),
    noteCountInput: document.getElementById('note-count-input'),
    difficultyControls: document.getElementById('difficulty-controls'),
    musicModeControls: document.getElementById('music-mode-controls'),
    chartFileNameEl: document.getElementById('chart-file-name'),
    musicFileNameEl: document.getElementById('music-file-name'),
    requiredMusicFileNameEl: document.getElementById('required-music-file-name'),
    screens: {
        menu: document.getElementById('menu-screen'),
        playing: document.getElementById('playing-screen'),
        result: document.getElementById('result-screen'),
        editor: document.getElementById('editor-screen'),
        settings: document.getElementById('settings-screen'),
    },
    messages: {
        menu: document.getElementById('menu-message'),
        editor: document.getElementById('editor-message'),
    },
    difficulty: {
        toggleBtn: document.getElementById('toggle-details-btn'),
        toggleIcon: document.querySelector('#toggle-details-btn svg'),
        detailsPanel: document.getElementById('detailed-difficulty-settings'),
        speedSlider: document.getElementById('note-speed-slider'),
        speedValue: document.getElementById('note-speed-value'),
        dongtaSlider: document.getElementById('dongta-prob-slider'),
        dongtaValue: document.getElementById('dongta-prob-value'),
        longNoteSlider: document.getElementById('long-note-prob-slider'),
        longNoteValue: document.getElementById('long-note-prob-value'),
        falseNoteToggle: document.getElementById('false-note-toggle'),
        falseNoteProbContainer: document.getElementById('false-note-prob-container'),
        falseNoteProbSlider: document.getElementById('false-note-prob-slider'),
        falseNoteProbValue: document.getElementById('false-note-prob-value'),
    },
    finalScoreEl: document.getElementById('final-score'),
    rankEl: document.getElementById('rank'),
    finalPerfectEl: document.getElementById('final-perfect'),
    finalGoodEl: document.getElementById('final-good'),
    finalBadEl: document.getElementById('final-bad'),
    finalMissEl: document.getElementById('final-miss'),
    editor: {
        container: document.getElementById('editor-container'),
        timeline: document.getElementById('editor-timeline'),
        gridContainer: document.getElementById('editor-grid-container'),
        notesContainer: document.getElementById('editor-notes-container'),
        playhead: document.getElementById('editor-playhead'),
        playhead: document.getElementById('editor-playhead'),
        
        // 상단 컨트롤
        audioFileInput: document.getElementById('audio-file-input-editor'),
        audioFileNameEl: document.getElementById('audio-file-name-editor'),
        startTimeInput: document.getElementById('editor-start-time'),
        bpmInput: document.getElementById('bpm-input'),
        addMeasureBtn: document.getElementById('editor-add-measure-btn'),
        removeMeasureBtn: document.getElementById('editor-remove-measure-btn'),
        noteTypeSelector: document.getElementById('editor-note-type-selector'),
        
        // 관리 버튼
        playBtn: document.getElementById('editor-play-btn'),
        stopBtn: document.getElementById('editor-stop-btn'),
        saveBtn: document.getElementById('editor-save-btn'),
        loadBtn: document.getElementById('editor-load-btn'),
        resetBtn: document.getElementById('editor-reset-btn'),
        backBtn: document.getElementById('editor-back-btn'),
        
        // 기타 UI
        loadInput: document.getElementById('editor-load-input'),
        statusLabel: document.getElementById('editor-status-label'),
    },
    pauseGameBtn: document.getElementById('pause-game-btn'),
    resumeGameBtn: document.getElementById('resume-game-btn'),
    playingStatusLabel: document.getElementById('playing-status-label'),
    settings: {
        iconMenu: document.getElementById('settings-icon-menu'),
        iconPlaying: document.getElementById('settings-icon-playing'),
        backBtn: document.getElementById('settings-back-btn'),
        tabsContainer: document.getElementById('settings-tabs'),
        tabContents: document.querySelectorAll('.tab-content'),
        musicVolumeSlider: document.getElementById('volume-slider-music'),
        musicVolumeValue: document.getElementById('volume-value-music'),
        sfxVolumeSlider: document.getElementById('volume-slider-sfx'),
        sfxVolumeValue: document.getElementById('volume-value-sfx'),
        controls: {
            keybindBoxes: document.querySelectorAll('.keybind-box'),
            statusLabel: document.getElementById('keybind-status-label'),
            saveBtn: document.getElementById('save-keybinds-btn')
        }
    }
};
