const DOM = {
    gameArea: document.getElementById('game-area'),
    uiArea: document.getElementById('ui-area'),
    lanesContainer: document.getElementById('lanes-container'),
    scoreEl: document.getElementById('score'),
    comboEl: document.getElementById('combo'),
    judgementTextEl: document.getElementById('judgement-text'),
    comboTextEl: document.getElementById('combo-text'),
    musicPlayer: document.getElementById('music-player'),
    countdownTextEl: document.getElementById('countdown-text'),
    noteCountContainer: document.getElementById('note-count-container'),
    noteCountInput: document.getElementById('note-count-input'),
    musicModeControls: document.getElementById('music-mode-controls'),
    chartFileNameEl: document.getElementById('chart-file-name'),
    musicFileNameEl: document.getElementById('music-file-name'),
    screens: {
        menu: document.getElementById('menu-screen'),
        playing: document.getElementById('playing-screen'),
        result: document.getElementById('result-screen'),
        editor: document.getElementById('editor-screen'),
    },
    messages: {
        menu: document.getElementById('menu-message'),
        editor: document.getElementById('editor-message'),
    },
    difficulty: {
        toggleBtn: document.getElementById('toggle-details-btn'),
        toggleIcon: document.querySelector('#toggle-details-btn svg'),
        detailsPanel: document.getElementById('detailed-difficulty-settings'),
        speedSlider: document.getElementById('note-speed-slider'),
        speedValue: document.getElementById('note-speed-value'),
        dongtaSlider: document.getElementById('dongta-prob-slider'),
        dongtaValue: document.getElementById('dongta-prob-value'),
        longNoteSlider: document.getElementById('long-note-prob-slider'),
        longNoteValue: document.getElementById('long-note-prob-value'),
    },
    finalScoreEl: document.getElementById('final-score'),
    rankEl: document.getElementById('rank'),
    finalPerfectEl: document.getElementById('final-perfect'),
    finalGoodEl: document.getElementById('final-good'),
    finalBadEl: document.getElementById('final-bad'),
    finalMissEl: document.getElementById('final-miss'),
    editor: {
        container: document.getElementById('editor-container'),
        timeline: document.getElementById('editor-timeline'),
        playhead: document.getElementById('editor-playhead'),
        audioFileInput: document.getElementById('audio-file-input-editor'),
        audioFileNameEl: document.getElementById('audio-file-name-editor'),
        bpmInput: document.getElementById('bpm-input'),
        lanesSelector: document.getElementById('editor-lanes-selector'),
        loadInput: document.getElementById('editor-load-input'),
        playPauseBtn: document.getElementById('editor-play-pause-btn'),
        saveBtn: document.getElementById('editor-save-btn'),
        loadBtn: document.getElementById('editor-load-btn'),
        backBtn: document.getElementById('editor-back-btn'),
    },
    pauseGameBtn: document.getElementById('pause-game-btn'),
    resumeGameBtn: document.getElementById('resume-game-btn'),
    playingStatusLabel: document.getElementById('playing-status-label'),
};